export type SiteLanguage = 'fr' | 'en' | 'es';
export type UnitSystem = 'metric' | 'imperial';

const messages: Record<SiteLanguage, Record<string, string>> = {
  fr: {},
  en: {
    'ACCUEIL': 'HOME',
    'MA COLLECTION': 'MY COLLECTION',
    'BOUTIQUE PACKS': 'BOOSTER SHOP',
    'MARKETPLACE': 'MARKETPLACE',
    'CONTRATS': 'MISSIONS',
    'PROFIL PILOTE': 'DRIVER PROFILE',
    'RÉGLAGES': 'SETTINGS',
    'ATELIER CARTES': 'CARD STUDIO',
    'ATELIER CIRCUITS': 'CIRCUIT STUDIO',
    'Season One': 'Season One',
    'Rang Actuel': 'Current Rank',
    'Écurie Platine': 'Platinum Garage',
    'XP PILOTE': 'DRIVER XP',
    'Se Connecter': 'Sign in',
    'Rejoignez l’élite Apex': 'Join the Apex elite',
    'Rejoignez l\'élite Apex': 'Join the Apex elite',
    'Réglages': 'Settings',
    'Paramètres du profil': 'Profile settings',
    'Langue': 'Language',
    'Unités': 'Units',
    'Français': 'French',
    'English': 'English',
    'Español': 'Spanish',
    'Métriques': 'Metric',
    'Impériales': 'Imperial',
    'Les préférences sont enregistrées sur votre profil.': 'Your preferences are saved to your profile.',
    'Enregistrement…': 'Saving…',
    'Préférences enregistrées.': 'Preferences saved.',
    'Impossible d’enregistrer la préférence.': 'Could not save this preference.',
    'Tableau de bord': 'Dashboard',
    'Gérez votre écurie et vos actifs.': 'Manage your garage and assets.',
    'Cartes totales': 'Total cards',
    'Dans votre collection': 'In your collection',
    'Modèles uniques': 'Unique models',
    'Garage distinct': 'Unique in your garage',
    'Balance AP': 'AP balance',
    'Disponibles': 'Available',
    'Niveau écurie': 'Garage level',
    'Prochaine récompense à +5': 'Next reward at +5',
    'Boosters Populaires': 'Popular boosters',
    'Voir toute la boutique': 'View the full shop',
    'Conseil du jour': 'Tip of the day',
    'Mon Garage': 'My Garage',
    'Collection complète des véhicules et circuits d’exception.': 'Your complete collection of exceptional cars and circuits.',
    'Collection': 'Collection',
    'Total Cartes': 'Total cards',
    'Exemplaires': 'Copies',
    'Tout': 'All',
    'Tous': 'All',
    'Véhicules': 'Cars',
    'Circuits': 'Circuits',
    'Rechercher une carte...': 'Search cards...',
    'Toutes les raretés': 'All rarities',
    'Commun': 'Common',
    'Inhabituel': 'Uncommon',
    'Épique': 'Epic',
    'Légendaire': 'Legendary',
    'Trier par Nom': 'Sort by Name',
    'Marques, A à Z': 'Makes, A to Z',
    'Marques, Z à A': 'Makes, Z to A',
    'IP, décroissant': 'PI, descending',
    'IP, croissant': 'PI, ascending',
    'Niveau, croissant': 'Level, ascending',
    'Niveau, décroissant': 'Level, descending',
    'Trier par Rareté': 'Sort by Rarity',
    'Plus récent': 'Newest',
    'Initialisation du garage...': 'Loading garage...',
    'Aucune carte trouvée pour ces critères.': 'No cards match these filters.',
    'Niveau': 'Level',
    'virages': 'turns',
    'ligne': 'straight',
    'Détails': 'Details',
    'Email': 'Email',
    'Toutes les Cartes': 'All Cards',
    'Filtrer par rareté :': 'Filter by rarity:',
    'Toutes': 'All',
    'Chargement des cartes...': 'Loading cards...',
    'Saison 1 · Édition Limitée': 'Season 1 · Limited Edition',
    'Collectionnez': 'Collect',
    'l’Élite Automobile': 'Automotive Elite',
    'l\'Élite Automobile': 'Automotive Elite',
    'Ouvrez des packs premium, construisez votre garage légendaire et dominez le marché mondial. Chaque carte est une icône automobile rare.': 'Open premium packs, build your legendary garage, and dominate the global market. Every card is a rare automotive icon.',
    'Commencer Gratuitement': 'Get Started for Free',
    'Cartes Uniques': 'Unique Cards',
    'Possibilités': 'Possibilities',
    'Trois Piliers d’Excellence': 'Three Pillars of Excellence',
    'Une expérience de collection premium avec des mécaniques de jeu avancées': 'A premium collecting experience with advanced game mechanics',
    'Système de Boosters Premium': 'Premium Booster System',
    'Des packs exclusifs pour tous les collectionneurs': 'Exclusive packs for every collector',
    'Pack Carbon, Icon & Legendary avec raretés exclusives': 'Carbon, Icon & Legendary packs with exclusive rarities',
    'Animation d’ouverture cinématique immersive': 'Immersive cinematic opening animation',
    'Cartes garanties selon la rareté du pack': 'Cards guaranteed according to pack rarity',
    'Distribution équilibrée avec anti-doublon intelligent': 'Balanced distribution with smart duplicate protection',
    'Marketplace Mondial': 'Global Marketplace',
    'Achetez, vendez et dominez l’économie': 'Buy, sell, and dominate the economy',
    'Transactions en Apex Points (AP) - Monnaie premium': 'Transactions in Apex Points (AP) — premium currency',
    'Fixez vos propres prix et stratégies de vente': 'Set your own prices and sales strategies',
    'Système anti-fraude et transactions sécurisées': 'Anti-fraud system and secure transactions',
    'Marché en temps réel avec autres collectionneurs': 'Real-time market with other collectors',
    'Missions & Contrats': 'Missions & Contracts',
    'Complétez des défis pour gagner des récompenses': 'Complete challenges to earn rewards',
    'Contrats quotidiens avec objectifs progressifs': 'Daily contracts with progressive objectives',
    'Récompenses en AP pour chaque mission complétée': 'AP rewards for every completed mission',
    'Suivi automatique de progression en temps réel': 'Automatic real-time progress tracking',
    'Défis spéciaux pour débloquer des cartes exclusives': 'Special challenges to unlock exclusive cards',
    'Rejoignez l’Élite': 'Join the Elite',
    'Rejoignez l\'Élite': 'Join the Elite',
    'Créez votre compte gratuitement et recevez votre premier pack de bienvenue pour démarrer votre collection.': 'Create your free account and receive your first welcome pack to start your collection.',
    'Créer mon Garage Elite': 'Create My Elite Garage',
    'Une erreur inattendue est survenue.': 'An unexpected error occurred.',
    'Une erreur est survenue lors de l’ouverture.': 'An error occurred while opening the booster.',
    'Fixer le prix': 'Set price',
    'Confirmer': 'Confirm',
    'Annuler': 'Cancel',
    'il y a 2h': '2h ago',
    'il y a 2 heures': '2 hours ago',
    'il y a 5 heures': '5 hours ago',
    'Locked': 'Locked',
    'Toutes les cartes': 'All Cards',
    'Rareté : Épique': 'Rarity: Epic',
    'Stat : +12 Prestige': 'Stat: +12 Prestige',
    'Home': 'Home',
    'Marché': 'Marketplace',
    'Settings': 'Settings',
    'Il y a 20% de chance dans le': 'There is a 20% chance in the',
    'N’oubliez pas d’échanger vos doublons au marché pour optimiser votre progression.': 'Remember to trade duplicate cards in the marketplace to optimize your progress.',
    '+150 AP collectés': '+150 AP collected',
    'Chasseur d\'Icônes': 'Icon Hunter',
    'Marketplace': 'Marketplace',
    'Retour à la boutique': 'Back to shop',
    'Retourner la carte {number}': 'Flip card {number}',
    'Succès débloqués': 'Achievements unlocked',
    'Le point d’entrée idéal. Contient principalement des cartes Standard.': 'The ideal starting pack. Contains mostly Standard cards.',
    'Un pack équilibré avec une meilleure fréquence de cartes rares.': 'A balanced pack with a higher rate of rare cards.',
    'Pour les collectionneurs sérieux. Taux de cartes Épiques doublé.': 'For serious collectors. Double the chance of Epic cards.',
    'Un pack premium orienté vers les cartes de haute performance.': 'A premium pack focused on high-performance cards.',
    'Une mécanique de tirage tournée vers les pièces exceptionnelles.': 'A pack focused on exceptional cars.',
    'Le plus haut niveau de tirage, réservé aux collectionneurs.': 'The highest tier, reserved for collectors.',
    'Le luxe absolu. Garanti au moins une carte Rare ou supérieure.': 'The ultimate luxury. Guaranteed at least one Rare card or higher.',
    'L’élite ultime. Seul pack contenant des cartes ICON.': 'The ultimate elite. The only pack containing ICON cards.',
    'Pack Commun': 'Common Pack',
    'Pack Inhabituel': 'Uncommon Pack',
    'Pack Rare': 'Rare Pack',
    'Pack Ultra Rare': 'Ultra Rare Pack',
    'Pack Prototype': 'Prototype Pack',
    'Pack Mythic': 'Mythic Pack',
    'Pack Légendaire': 'Legendary Pack',
    'Pack Carbon': 'Carbon Pack',
    'Annonce créée avec succès !': 'Listing created successfully!',
    'Les cartes de rareté': 'Cards with the rarity',
    'Icon': 'Icon',
    'Apprenti Collectionneur': 'Collector Apprentice',
    'Ouvrez votre premier pack de boosters.': 'Open your first booster pack.',
    'Vendeur Agile': 'Quick Seller',
    'Listez une carte sur le Marketplace.': 'List a card on the marketplace.',
    'Chasseur d’icônes': 'Icon Hunter',
    'Possédez une carte de rareté Icon.': 'Own an Icon rarity card.',
    'Le point d\'entrée idéal. Contient principalement des cartes Standard.': 'The ideal starting pack. Contains mostly Standard cards.',
    'L\'élite ultime. Seul pack contenant des cartes ICON.': 'The ultimate elite. The only pack containing ICON cards.',
    'Une erreur est survenue lors de l\'ouverture.': 'An error occurred while opening the booster.',
    'Nouveau moteur': 'New engine',
    'Déchirer de gauche à droite': 'Tear from left to right',
    'Faire glisser de gauche à droite pour déchirer le booster': 'Drag from left to right to tear open the booster',
    'Ouvrir le booster': 'Open booster',
    'Ouverture en cours...': 'Opening...',
    'Attrape la languette et fais-la glisser jusqu’au bord droit.': 'Grab the tab and drag it all the way to the right.',
    'Tes cartes sont là !': 'Your cards are here!',
    'Clique sur une carte pour la retourner, ou révèle-les toutes.': 'Click a card to flip it, or reveal them all.',
    'Retourner les cartes face cachée': 'Flip all cards face down',
    'Retourner toutes les cartes': 'Flip all cards',
    'Retourner la carte': 'Flip card',
    'Cliquez pour révéler': 'Click to reveal',
    'Retourner au garage': 'Back to garage',
    'Centre des Succès': 'Achievement Center',
    'Suivez votre progression et vos exploits sur la piste.': 'Track your progress and achievements on the track.',
    'Maître de Collection': 'Master Collector',
    'Continuez à débloquer des succès pour obtenir des récompenses exclusives et monter dans le classement mondial des pilotes.': 'Keep unlocking achievements to earn exclusive rewards and climb the global driver rankings.',
    '3 / 6 SUCCÈS DÉBLOQUÉS': '3 / 6 ACHIEVEMENTS UNLOCKED',
    'RANG: PILOTE AMATEUR': 'RANK: AMATEUR DRIVER',
    'Premières Roues': 'First Wheels',
    'Posséder votre premier véhicule.': 'Own your first vehicle.',
    'Chasseur de Légendes': 'Legend Hunter',
    'Obtenir une carte de rareté Legend.': 'Get a Legend rarity card.',
    'Globe-Trotteur': 'Globetrotter',
    'Débloquer 10 circuits différents.': 'Unlock 10 different circuits.',
    'Millionnaire': 'Millionaire',
    'Atteindre un solde de 1,000,000 Crédits.': 'Reach a balance of 1,000,000 Credits.',
    'Garage Complet': 'Complete Garage',
    'Posséder au moins un exemplaire de chaque modèle.': 'Own at least one copy of every model.',
    'Accroc à la Boutique': 'Shopaholic',
    'Ouvrir plus de 100 boosters.': 'Open more than 100 boosters.',
    'Débloqué le': 'Unlocked on',
    'Posséder 10 cartes – Booster offert': 'Own 10 cards — free booster',
    'Premier booster ouvert': 'First booster opened',
    'Accéder au marché': 'Access the marketplace',
    'Boutique Officielle': 'Official Shop',
    'Débloquez de nouvelles mécaniques et agrandissez votre garage.': 'Unlock new mechanics and expand your garage.',
    'Votre Solde': 'Your balance',
    'Contient': 'Contains',
    'cartes aléatoires': 'random cards',
    'Apex Points': 'Apex Points',
    'Solde Insuffisant': 'Insufficient balance',
    'Acheter le pack': 'Buy booster',
    'Contrats de Pilote': 'Driver Missions',
    'Remplissez vos objectifs pour financer votre écurie.': 'Complete objectives to fund your garage.',
    'Progression': 'Progress',
    'Réclamer la récompense': 'Claim reward',
    'Récompense récupérée': 'Reward claimed',
    'Aucune mission disponible': 'No missions available',
    'Échangez et achetez des pièces rares pour votre écurie.': 'Trade and buy rare parts for your garage.',
    'Parcourir': 'Browse',
    'Mes Ventes': 'My Listings',
    'Rechercher une rareté, une marque...': 'Search rarity, make...',
    'Filtres': 'Filters',
    'Vendre une carte': 'Sell a card',
    'Ouverture du marché...': 'Opening marketplace...',
    'Prix d’achat': 'Purchase price',
    'Acheter': 'Buy',
    'Guide du pilote': 'Driver guide',
    'How to play': 'How to play',
    'Constituez votre collection automobile, suivez vos missions et utilisez les Apex Points pour ouvrir des packs ou échanger des cartes.': 'Build your car collection, track your missions, and use Apex Points to open boosters or trade cards.',
    'Créez votre compte': 'Create your account',
    'Ouvrez des boosters': 'Open boosters',
    'Explorez votre garage': 'Explore your garage',
    'Suivez vos missions': 'Track your missions',
    'Parcourez le marché': 'Browse the marketplace',
    'Connexion': 'Sign in',
    'Voir les boosters': 'View boosters',
    'Ouvrir le garage': 'Open garage',
    'Voir les missions': 'View missions',
    'Visiter le marketplace': 'Visit marketplace',
    'Accès Pilote': 'Driver Sign In',
    'Nouvelle Écurie': 'New Garage',
    'Mot de passe': 'Password',
    'Créer l’écurie': 'Create garage',
    'Créer l\'écurie': 'Create garage',
    'Inscrivez-vous': 'Create an account',
    'Connectez-vous': 'Sign in',
    'Chargement système...': 'Loading...',
    'Véhicule': 'Vehicle',
    'Circuit': 'Circuit',
    'Pays': 'Country',
    'Année': 'Year',
    'Marque': 'Make',
    'Modèle': 'Model',
    'Puissance': 'Power',
    'Couple': 'Torque',
    'Poids': 'Weight',
    'Transmission': 'Transmission',
    'Indice de performance (IP)': 'Performance Index (PI)',
    'Vitesse maximale': 'Top speed',
    'Prix neuf': 'New price',
    'Carburant': 'Fuel',
    'Régime maximal': 'Max RPM',
    'Exemplaires vendus (monde)': 'Units sold worldwide',
    'Cylindrée': 'Engine displacement',
    'Cylindres': 'Cylinders',
    'Aspiration': 'Aspiration',
    'Atmosphérique': 'Naturally aspirated',
    'Longueur': 'Length',
    'Virages': 'Turns',
    'Ligne droite': 'Straight',
    'Type': 'Type',
    'Fermer les détails': 'Close details',
    'exemplaire': 'copy',
    'exemplaires': 'copies',
    'possédé': 'owned',
    'possédés': 'owned',
    '0 à 100 km/h': '0–100 km/h',
    'Vitesse Max': 'Top speed',
    'Se déconnecter': 'Sign out',
    'Editer Profil': 'Profile settings',
    'PILOTE OFFICIEL APEX': 'OFFICIAL APEX DRIVER',
    'Balance Actuelle': 'Current Balance',
    'Recharger mon compte': 'Top up my account',
    'Cartes Collection': 'Cards Collected',
    'Niveau Pilote': 'Driver Level',
    'Activité Récente': 'Recent Activity',
    'Badges Débloqués': 'Badges Unlocked',
    'Ouverture de Booster': 'Booster Opened',
    'Pack Standard ouvert dans la boutique': 'Standard Pack opened in the shop',
    'Nouvelle Carte': 'New Card',
    'ajoutée au garage': 'added to your garage',
    'Bonus Journalier': 'Daily Bonus',
    'Hier': 'Yesterday',
    'Premier Circuit': 'First Circuit',
    'Collectionneur': 'Collector',
    'Accro au Boost': 'Booster Fan',
    'Carte introuvable': 'Card not found',
    'Retour au garage': 'Back to garage',
    'Ajouter aux favoris': 'Add to favorites',
    'Moteur': 'Engine',
    'Induction': 'Induction',
    'Ce chef-d’œuvre technologique repousse les limites de la performance et du design.': 'This technological masterpiece pushes the limits of performance and design.',
    'Aucun contrat disponible pour le moment.': 'No missions are available right now.',
    'Contrat Honoré': 'Mission completed',
    'Veuillez vous connecter pour acheter.': 'Please sign in to buy.',
    'Solde AP insuffisant.': 'Insufficient AP balance.',
    'Voulez-vous acheter cette carte pour {price} AP ?': 'Do you want to buy this card for {price} AP?',
    'Achat réussi ! La carte a été ajoutée à votre garage.': 'Purchase successful! The card has been added to your garage.',
    'Erreur': 'Error',
    'Mettre en vente': 'List for sale',
    'Sélectionnez une pièce de votre garage': 'Select an item from your garage',
    'Votre garage est vide': 'Your garage is empty',
    'Carte': 'Card',
    'Image indisponible': 'No image',
    'Accueil': 'Home',
    'Garage': 'Garage',
    'Cartes': 'Cards',
    'Boosters': 'Boosters',
    'Succès': 'Achievements',
    'Profil': 'Profile',
    'Navigation de pied de page': 'Footer navigation',
    'Erreur inattendue': 'Unexpected error',
    'Aucun résultat': 'No results',
    'nom@ecurie.com': 'name@garage.com',
    'Connectez-vous pour accéder à votre profil et aux actions réservées aux joueurs, comme l’ouverture de boosters, les missions et les transactions du marché.': 'Sign in to access your profile and player features like opening boosters, missions, and marketplace transactions.',
    'Choisissez un pack dans la boutique et dépensez les Apex Points (AP) affichés. Chaque pack contient un nombre de cartes aléatoires ; les cartes obtenues sont ajoutées à votre collection.': 'Choose a pack in the shop and spend the displayed Apex Points (AP). Each pack contains random cards, which are added to your collection.',
    'Le garage rassemble les véhicules et les circuits du catalogue. Recherchez et filtrez les cartes, puis ouvrez une carte pour consulter ses détails et votre nombre d’exemplaires.': 'Your garage contains all vehicles and circuits in the catalogue. Search and filter cards, then open one to view its details and the number you own.',
    'Les missions affichent leur objectif, leur progression et leur récompense. Lorsqu’une mission est terminée, récupérez les AP depuis cette page.': 'Missions show their objective, progress, and reward. Claim your AP here when a mission is complete.',
    'Consultez les cartes mises en vente par les joueurs, achetez-les avec vos AP ou proposez vos propres cartes à la vente.': 'Browse cards listed by players, buy them with AP, or list your own cards for sale.',
    'Parcourir le marketplace': 'Browse the marketplace',
    'Achetez et vendez des cartes': 'Buy and sell cards',
  },
  es: {
    'ACCUEIL': 'INICIO',
    'MA COLLECTION': 'MI COLECCIÓN',
    'BOUTIQUE PACKS': 'TIENDA DE SOBRES',
    'MARKETPLACE': 'MERCADO',
    'CONTRATS': 'MISIONES',
    'PROFIL PILOTE': 'PERFIL DE PILOTO',
    'RÉGLAGES': 'AJUSTES',
    'ATELIER CARTES': 'TALLER DE CARTAS',
    'ATELIER CIRCUITS': 'TALLER DE CIRCUITOS',
    'Season One': 'Temporada Uno',
    'Rang Actuel': 'Rango actual',
    'Écurie Platine': 'Garaje Platino',
    'XP PILOTE': 'EXP. DE PILOTO',
    'Se Connecter': 'Iniciar sesión',
    'Rejoignez l’élite Apex': 'Únete a la élite Apex',
    'Rejoignez l\'élite Apex': 'Únete a la élite Apex',
    'Réglages': 'Ajustes',
    'Paramètres du profil': 'Ajustes del perfil',
    'Langue': 'Idioma',
    'Unités': 'Unidades',
    'Français': 'Francés',
    'English': 'Inglés',
    'Español': 'Español',
    'Métriques': 'Métricas',
    'Impériales': 'Imperiales',
    'Les préférences sont enregistrées sur votre profil.': 'Tus preferencias se guardan en tu perfil.',
    'Enregistrement…': 'Guardando…',
    'Préférences enregistrées.': 'Preferencias guardadas.',
    'Impossible d’enregistrer la préférence.': 'No se pudo guardar esta preferencia.',
    'Tableau de bord': 'Panel',
    'Gérez votre écurie et vos actifs.': 'Administra tu garaje y tus activos.',
    'Cartes totales': 'Cartas totales',
    'Dans votre collection': 'En tu colección',
    'Modèles uniques': 'Modelos únicos',
    'Garage distinct': 'Modelos distintos',
    'Balance AP': 'Saldo de AP',
    'Disponibles': 'Disponibles',
    'Niveau écurie': 'Nivel del garaje',
    'Prochaine récompense à +5': 'Próxima recompensa en +5',
    'Boosters Populaires': 'Sobres populares',
    'Voir toute la boutique': 'Ver toda la tienda',
    'Conseil du jour': 'Consejo del día',
    'Mon Garage': 'Mi garaje',
    'Collection complète des véhicules et circuits d’exception.': 'Colección completa de vehículos y circuitos excepcionales.',
    'Collection': 'Colección',
    'Total Cartes': 'Cartas totales',
    'Exemplaires': 'Copias',
    'Tout': 'Todo',
    'Tous': 'Todos',
    'Véhicules': 'Vehículos',
    'Circuits': 'Circuitos',
    'Rechercher une carte...': 'Buscar cartas...',
    'Toutes les raretés': 'Todas las rarezas',
    'Commun': 'Común',
    'Inhabituel': 'Poco común',
    'Épique': 'Épica',
    'Légendaire': 'Legendaria',
    'Trier par Nom': 'Ordenar por nombre',
    'Marques, A à Z': 'Marcas, A a Z',
    'Marques, Z à A': 'Marcas, Z a A',
    'IP, décroissant': 'IR, descendente',
    'IP, croissant': 'IR, ascendente',
    'Niveau, croissant': 'Nivel, ascendente',
    'Niveau, décroissant': 'Nivel, descendente',
    'Trier par Rareté': 'Ordenar por rareza',
    'Plus récent': 'Más reciente',
    'Initialisation du garage...': 'Cargando garaje...',
    'Aucune carte trouvée pour ces critères.': 'No hay cartas que coincidan con estos filtros.',
    'Niveau': 'Nivel',
    'virages': 'curvas',
    'ligne': 'recta',
    'Détails': 'Detalles',
    'Email': 'Correo electrónico',
    'Toutes les Cartes': 'Todas las cartas',
    'Filtrer par rareté :': 'Filtrar por rareza:',
    'Toutes': 'Todas',
    'Chargement des cartes...': 'Cargando cartas...',
    'Saison 1 · Édition Limitée': 'Temporada 1 · Edición limitada',
    'Collectionnez': 'Colecciona',
    'l’Élite Automobile': 'la élite del automóvil',
    'l\'Élite Automobile': 'la élite del automóvil',
    'Ouvrez des packs premium, construisez votre garage légendaire et dominez le marché mondial. Chaque carte est une icône automobile rare.': 'Abre sobres premium, construye tu garaje legendario y domina el mercado mundial. Cada carta es un icono automovilístico único.',
    'Commencer Gratuitement': 'Empezar gratis',
    'Cartes Uniques': 'Cartas únicas',
    'Possibilités': 'Posibilidades',
    'Trois Piliers d’Excellence': 'Tres pilares de excelencia',
    'Une expérience de collection premium avec des mécaniques de jeu avancées': 'Una experiencia de colección premium con mecánicas de juego avanzadas',
    'Système de Boosters Premium': 'Sistema premium de sobres',
    'Des packs exclusifs pour tous les collectionneurs': 'Sobres exclusivos para todos los coleccionistas',
    'Pack Carbon, Icon & Legendary avec raretés exclusives': 'Sobres Carbon, Icon y Legendary con rarezas exclusivas',
    'Animation d’ouverture cinématique immersive': 'Animación cinematográfica inmersiva',
    'Cartes garanties selon la rareté du pack': 'Cartas garantizadas según la rareza del sobre',
    'Distribution équilibrée avec anti-doublon intelligent': 'Distribución equilibrada con protección inteligente contra duplicados',
    'Marketplace Mondial': 'Mercado mundial',
    'Achetez, vendez et dominez l’économie': 'Compra, vende y domina la economía',
    'Transactions en Apex Points (AP) - Monnaie premium': 'Transacciones en Apex Points (AP), moneda premium',
    'Fixez vos propres prix et stratégies de vente': 'Define tus precios y estrategias de venta',
    'Système anti-fraude et transactions sécurisées': 'Sistema antifraude y transacciones seguras',
    'Marché en temps réel avec autres collectionneurs': 'Mercado en tiempo real con otros coleccionistas',
    'Missions & Contrats': 'Misiones y contratos',
    'Complétez des défis pour gagner des récompenses': 'Completa desafíos para ganar recompensas',
    'Contrats quotidiens avec objectifs progressifs': 'Contratos diarios con objetivos progresivos',
    'Récompenses en AP pour chaque mission complétée': 'Recompensas de AP por cada misión completada',
    'Suivi automatique de progression en temps réel': 'Seguimiento automático del progreso en tiempo real',
    'Défis spéciaux pour débloquer des cartes exclusives': 'Desafíos especiales para desbloquear cartas exclusivas',
    'Rejoignez l’Élite': 'Únete a la élite',
    'Rejoignez l\'Élite': 'Únete a la élite',
    'Créez votre compte gratuitement et recevez votre premier pack de bienvenue pour démarrer votre collection.': 'Crea una cuenta gratis y recibe tu primer sobre de bienvenida para comenzar tu colección.',
    'Créer mon Garage Elite': 'Crear mi garaje élite',
    'Une erreur inattendue est survenue.': 'Se produjo un error inesperado.',
    'Une erreur est survenue lors de l’ouverture.': 'Se produjo un error al abrir el sobre.',
    'Fixer le prix': 'Fijar precio',
    'Confirmer': 'Confirmar',
    'Annuler': 'Cancelar',
    'il y a 2h': 'hace 2 h',
    'il y a 2 heures': 'hace 2 horas',
    'il y a 5 heures': 'hace 5 horas',
    'Locked': 'Bloqueado',
    'Toutes les cartes': 'Todas las cartas',
    'Rareté : Épique': 'Rareza: Épica',
    'Stat : +12 Prestige': 'Estadística: +12 prestigio',
    'Home': 'Inicio',
    'Marché': 'Mercado',
    'Settings': 'Ajustes',
    'Il y a 20% de chance dans le': 'Hay un 20 % de probabilidad en el',
    'N’oubliez pas d’échanger vos doublons au marché pour optimiser votre progression.': 'Recuerda intercambiar las cartas duplicadas en el mercado para avanzar.',
    '+150 AP collectés': '+150 AP obtenidos',
    'Apprenti Collectionneur': 'Aprendiz coleccionista',
    'Ouvrez votre premier pack de boosters.': 'Abre tu primer sobre.',
    'Vendeur Agile': 'Vendedor ágil',
    'Listez une carte sur le Marketplace.': 'Pon una carta a la venta en el mercado.',
    'Chasseur d’Icônes': 'Cazador de iconos',
    'Possédez une carte de rareté Icon.': 'Consigue una carta de rareza Icon.',
    'Marketplace': 'Mercado',
    'Retour à la boutique': 'Volver a la tienda',
    'Retourner la carte {number}': 'Voltear carta {number}',
    'Succès débloqués': 'Logros desbloqueados',
    'Le point d’entrée idéal. Contient principalement des cartes Standard.': 'El sobre ideal para empezar. Contiene principalmente cartas estándar.',
    'Un pack équilibré avec une meilleure fréquence de cartes rares.': 'Un sobre equilibrado con mayor probabilidad de cartas raras.',
    'Pour les collectionneurs sérieux. Taux de cartes Épiques doublé.': 'Para coleccionistas serios. Duplica la probabilidad de cartas épicas.',
    'Un pack premium orienté vers les cartes de haute performance.': 'Un sobre premium centrado en vehículos de alto rendimiento.',
    'Une mécanique de tirage tournée vers les pièces exceptionnelles.': 'Un sobre centrado en vehículos excepcionales.',
    'Le plus haut niveau de tirage, réservé aux collectionneurs.': 'El nivel más alto, reservado para coleccionistas.',
    'Le luxe absolu. Garanti au moins une carte Rare ou supérieure.': 'Lujo absoluto. Garantiza al menos una carta Rare o superior.',
    'L’élite ultime. Seul pack contenant des cartes ICON.': 'La élite definitiva. El único sobre con cartas ICON.',
    'Pack Commun': 'Sobre común',
    'Pack Inhabituel': 'Sobre poco común',
    'Pack Rare': 'Sobre raro',
    'Pack Ultra Rare': 'Sobre ultra raro',
    'Pack Prototype': 'Sobre prototipo',
    'Pack Mythic': 'Sobre mítico',
    'Pack Légendaire': 'Sobre legendario',
    'Pack Carbon': 'Sobre Carbon',
    'Annonce créée avec succès !': '¡Anuncio creado correctamente!',
    'Les cartes de rareté': 'Las cartas de rareza',
    'Icon': 'Icon',
    'Chasseur d\'Icônes': 'Cazador de iconos',
    'Le point d\'entrée idéal. Contient principalement des cartes Standard.': 'El sobre ideal para empezar. Contiene principalmente cartas estándar.',
    'L\'élite ultime. Seul pack contenant des cartes ICON.': 'La élite definitiva. El único sobre con cartas ICON.',
    'Une erreur est survenue lors de l\'ouverture.': 'Se produjo un error al abrir el sobre.',
    'Déchirer de gauche à droite': 'Abrir de izquierda a derecha',
    'Faire glisser de gauche à droite pour déchirer le booster': 'Desliza de izquierda a derecha para abrir el sobre',
    'Ouvrir le booster': 'Abrir sobre',
    'Ouverture en cours...': 'Abriendo...',
    'Attrape la languette et fais-la glisser jusqu’au bord droit.': 'Sujeta la pestaña y deslízala hasta el borde derecho.',
    'Tes cartes sont là !': '¡Tus cartas están aquí!',
    'Clique sur une carte pour la retourner, ou révèle-les toutes.': 'Pulsa una carta para voltearla o revélalas todas.',
    'Retourner les cartes face cachée': 'Ocultar todas las cartas',
    'Retourner toutes les cartes': 'Revelar todas las cartas',
    'Retourner la carte': 'Voltear carta',
    'Cliquez pour révéler': 'Pulsa para revelar',
    'Retourner au garage': 'Volver al garaje',
    'Centre des Succès': 'Centro de logros',
    'Suivez votre progression et vos exploits sur la piste.': 'Sigue tu progreso y tus logros en la pista.',
    'Maître de Collection': 'Maestro coleccionista',
    'Continuez à débloquer des succès pour obtenir des récompenses exclusives et monter dans le classement mondial des pilotes.': 'Sigue desbloqueando logros para obtener recompensas exclusivas y subir en la clasificación mundial.',
    '3 / 6 SUCCÈS DÉBLOQUÉS': '3 / 6 LOGROS DESBLOQUEADOS',
    'RANG: PILOTE AMATEUR': 'RANGO: PILOTO AFICIONADO',
    'Premières Roues': 'Primeras ruedas',
    'Posséder votre premier véhicule.': 'Consigue tu primer vehículo.',
    'Chasseur de Légendes': 'Cazador de leyendas',
    'Obtenir une carte de rareté Legend.': 'Consigue una carta de rareza Legend.',
    'Globe-Trotteur': 'Trotamundos',
    'Débloquer 10 circuits différents.': 'Desbloquea 10 circuitos distintos.',
    'Millionnaire': 'Millonario',
    'Atteindre un solde de 1,000,000 Crédits.': 'Alcanza un saldo de 1.000.000 créditos.',
    'Garage Complet': 'Garaje completo',
    'Posséder au moins un exemplaire de chaque modèle.': 'Consigue al menos una copia de cada modelo.',
    'Accroc à la Boutique': 'Adicto a la tienda',
    'Ouvrir plus de 100 boosters.': 'Abre más de 100 sobres.',
    'Débloqué le': 'Desbloqueado el',
    'Posséder 10 cartes – Booster offert': 'Consigue 10 cartas: sobre gratis',
    'Premier booster ouvert': 'Primer sobre abierto',
    'Accéder au marché': 'Acceder al mercado',
    'Boutique Officielle': 'Tienda oficial',
    'Débloquez de nouvelles mécaniques et agrandissez votre garage.': 'Desbloquea nuevas mecánicas y amplía tu garaje.',
    'Votre Solde': 'Tu saldo',
    'Contient': 'Contiene',
    'cartes aléatoires': 'cartas aleatorias',
    'Apex Points': 'Apex Points',
    'Solde Insuffisant': 'Saldo insuficiente',
    'Acheter le pack': 'Comprar sobre',
    'Contrats de Pilote': 'Misiones de piloto',
    'Remplissez vos objectifs pour financer votre écurie.': 'Completa objetivos para financiar tu garaje.',
    'Progression': 'Progreso',
    'Réclamer la récompense': 'Reclamar recompensa',
    'Récompense récupérée': 'Recompensa obtenida',
    'Aucune mission disponible': 'No hay misiones disponibles',
    'Échangez et achetez des pièces rares pour votre écurie.': 'Intercambia y compra piezas raras para tu garaje.',
    'Parcourir': 'Explorar',
    'Mes Ventes': 'Mis ventas',
    'Rechercher une rareté, une marque...': 'Buscar rareza, marca...',
    'Filtres': 'Filtros',
    'Vendre une carte': 'Vender una carta',
    'Ouverture du marché...': 'Abriendo el mercado...',
    'Prix d’achat': 'Precio de compra',
    'Acheter': 'Comprar',
    'Guide du pilote': 'Guía del piloto',
    'How to play': 'Cómo jugar',
    'Constituez votre collection automobile, suivez vos missions et utilisez les Apex Points pour ouvrir des packs ou échanger des cartes.': 'Construye tu colección de coches, sigue tus misiones y usa Apex Points para abrir sobres o intercambiar cartas.',
    'Créez votre compte': 'Crea tu cuenta',
    'Ouvrez des boosters': 'Abre sobres',
    'Explorez votre garage': 'Explora tu garaje',
    'Suivez vos missions': 'Sigue tus misiones',
    'Parcourez le marché': 'Explora el mercado',
    'Connexion': 'Iniciar sesión',
    'Voir les boosters': 'Ver sobres',
    'Ouvrir le garage': 'Abrir garaje',
    'Voir les missions': 'Ver misiones',
    'Visiter le marketplace': 'Visitar el mercado',
    'Accès Pilote': 'Acceso de piloto',
    'Nouvelle Écurie': 'Nuevo garaje',
    'Mot de passe': 'Contraseña',
    'Créer l’écurie': 'Crear garaje',
    'Créer l\'écurie': 'Crear garaje',
    'Inscrivez-vous': 'Crear una cuenta',
    'Connectez-vous': 'Iniciar sesión',
    'Chargement système...': 'Cargando sistema...',
    'Véhicule': 'Vehículo',
    'Circuit': 'Circuito',
    'Pays': 'País',
    'Année': 'Año',
    'Marque': 'Marca',
    'Modèle': 'Modelo',
    'Puissance': 'Potencia',
    'Couple': 'Par motor',
    'Poids': 'Peso',
    'Transmission': 'Transmisión',
    'Indice de performance (IP)': 'Índice de rendimiento (IR)',
    'Vitesse maximale': 'Velocidad máxima',
    'Prix neuf': 'Precio nuevo',
    'Carburant': 'Combustible',
    'Régime maximal': 'Régimen máximo',
    'Exemplaires vendus (monde)': 'Unidades vendidas en el mundo',
    'Cylindrée': 'Cilindrada',
    'Cylindres': 'Cilindros',
    'Aspiration': 'Aspiración',
    'Atmosphérique': 'Atmosférico',
    'Longueur': 'Longitud',
    'Virages': 'Curvas',
    'Ligne droite': 'Recta',
    'Type': 'Tipo',
    'Fermer les détails': 'Cerrar detalles',
    'exemplaire': 'copia',
    'exemplaires': 'copias',
    'possédé': 'en propiedad',
    'possédés': 'en propiedad',
    '0 à 100 km/h': '0–100 km/h',
    'Vitesse Max': 'Velocidad máxima',
    'Se déconnecter': 'Cerrar sesión',
    'Editer Profil': 'Ajustes del perfil',
    'PILOTE OFFICIEL APEX': 'PILOTO OFICIAL APEX',
    'Balance Actuelle': 'Saldo actual',
    'Recharger mon compte': 'Recargar mi cuenta',
    'Cartes Collection': 'Cartas coleccionadas',
    'Niveau Pilote': 'Nivel de piloto',
    'Activité Récente': 'Actividad reciente',
    'Badges Débloqués': 'Insignias desbloqueadas',
    'Ouverture de Booster': 'Sobre abierto',
    'Pack Standard ouvert dans la boutique': 'Sobre estándar abierto en la tienda',
    'Nouvelle Carte': 'Nueva carta',
    'ajoutée au garage': 'añadida al garaje',
    'Bonus Journalier': 'Bono diario',
    'Hier': 'Ayer',
    'Premier Circuit': 'Primer circuito',
    'Collectionneur': 'Coleccionista',
    'Accro au Boost': 'Fan de los sobres',
    'Carte introuvable': 'Carta no encontrada',
    'Retour au garage': 'Volver al garaje',
    'Mettre en vente': 'Poner a la venta',
    'Ajouter aux favoris': 'Añadir a favoritos',
    'Moteur': 'Motor',
    'Induction': 'Admisión',
    'Ce chef-d’œuvre technologique repousse les limites de la performance et du design.': 'Esta obra tecnológica supera los límites del rendimiento y el diseño.',
    'Aucun contrat disponible pour le moment.': 'No hay misiones disponibles ahora.',
    'Contrat Honoré': 'Misión completada',
    'Veuillez vous connecter pour acheter.': 'Inicia sesión para comprar.',
    'Solde AP insuffisant.': 'Saldo de AP insuficiente.',
    'Voulez-vous acheter cette carte pour {price} AP ?': '¿Quieres comprar esta carta por {price} AP?',
    'Achat réussi ! La carte a été ajoutée à votre garage.': '¡Compra realizada! La carta se añadió a tu garaje.',
    'Erreur': 'Error',
    'Sélectionnez une pièce de votre garage': 'Selecciona una pieza de tu garaje',
    'Votre garage est vide': 'Tu garaje está vacío',
    'Carte': 'Carta',
    'Image indisponible': 'Imagen no disponible',
    'Accueil': 'Inicio',
    'Garage': 'Garaje',
    'Cartes': 'Cartas',
    'Boosters': 'Sobres',
    'Succès': 'Logros',
    'Profil': 'Perfil',
    'Navigation de pied de page': 'Navegación del pie de página',
    'Aucun résultat': 'Sin resultados',
    'Connectez-vous pour accéder à votre profil et aux actions réservées aux joueurs, comme l’ouverture de boosters, les missions et les transactions du marché.': 'Inicia sesión para acceder a tu perfil y a funciones como abrir sobres, las misiones y las transacciones del mercado.',
    'Choisissez un pack dans la boutique et dépensez les Apex Points (AP) affichés. Chaque pack contient un nombre de cartes aléatoires ; les cartes obtenues sont ajoutées à votre collection.': 'Elige un sobre en la tienda y gasta los Apex Points (AP) indicados. Cada sobre contiene cartas aleatorias que se añaden a tu colección.',
    'Le garage rassemble les véhicules et les circuits du catalogue. Recherchez et filtrez les cartes, puis ouvrez une carte pour consulter ses détails et votre nombre d’exemplaires.': 'El garaje reúne los vehículos y circuitos del catálogo. Busca y filtra cartas, y abre una para ver sus detalles y cuántas tienes.',
    'Les missions affichent leur objectif, leur progression et leur récompense. Lorsqu’une mission est terminée, récupérez les AP depuis cette page.': 'Las misiones muestran sus objetivos, progreso y recompensa. Reclama tus AP aquí cuando completes una misión.',
    'Consultez les cartes mises en vente par les joueurs, achetez-les avec vos AP ou proposez vos propres cartes à la vente.': 'Consulta las cartas a la venta, cómpralas con tus AP o pon tus cartas a la venta.',
  },
};

export function translate(language: SiteLanguage, message: string, values?: Record<string, string | number>) {
  const translated = messages[language][message] ?? message;
  return values
    ? translated.replace(/\{(\w+)\}/g, (match, key: string) => String(values[key] ?? match))
    : translated;
}

export function formatSpeed(value: number, units: UnitSystem, language: SiteLanguage = 'fr') {
  return units === 'imperial'
    ? `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(value * 0.621371)} mph`
    : `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(value)} km/h`;
}

export function formatPower(powerHp: number, units: UnitSystem, language: SiteLanguage = 'fr', powerKw?: number | null) {
  return units === 'metric'
    ? `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(powerKw ?? powerHp * 0.7457)} kW`
    : `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(powerHp)} HP`;
}

export function formatTorque(value: number, units: UnitSystem, language: SiteLanguage = 'fr') {
  return units === 'imperial'
    ? `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(value * 0.737562)} lb-ft`
    : `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(value)} Nm`;
}

export function formatWeight(value: number, units: UnitSystem, language: SiteLanguage = 'fr') {
  if (units === 'imperial') {
    const pounds = value > 50 ? value * 2.20462 : value * 2204.62;
    return `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(pounds)} lb`;
  }
  const kilograms = value > 50 ? value : value * 1000;
  return `${new Intl.NumberFormat(language, { maximumFractionDigits: 0 }).format(kilograms)} kg`;
}

export function formatDistance(value: number, units: UnitSystem, language: SiteLanguage = 'fr') {
  return units === 'imperial'
    ? `${new Intl.NumberFormat(language, { maximumFractionDigits: 1 }).format(value * 0.621371)} mi`
    : `${new Intl.NumberFormat(language, { maximumFractionDigits: 1 }).format(value)} km`;
}
