image:
  file: .gitpod.Dockerfile # optionnel, supprime si pas besoin

tasks:
  - init: npm ci
  - command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode

# optional: prebuilds configuration (enable in Gitpod dashboard)
