ALTER TABLE public.cards
  ADD COLUMN IF NOT EXISTS transmission TEXT,
  ADD COLUMN IF NOT EXISTS new_price_eur NUMERIC,
  ADD COLUMN IF NOT EXISTS fuel_type TEXT,
  ADD COLUMN IF NOT EXISTS max_rpm INTEGER,
  ADD COLUMN IF NOT EXISTS units_sold BIGINT;
